version = 0.1
[default.deploy.parameters]
stack_name = "optimiser-function-test"
resolve_s3 = true
s3_prefix = "optimiser-function-test"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = [
    "ImageVersion=''"
]