AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Tracing: Active
      AutoPublishAlias: live
      Timeout: 300
    Metadata:
      Dockerfile: dockerfile
      DockerContext: ./src
      DockerTag: "v0.0.1"

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Lambda}'
      RetentionInDays: 30

Outputs:
    LambdaArn:
        Description: "Lambda Function ARN"
        Value: !GetAtt Lambda.Arn
        Export:
          Name: OptimiserLambdaArn