name: Deploy SAM Application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch


jobs:

  BuildContainer:
    name: Build Container
    uses: ./.github/workflows/build-container.yaml
    permissions:
      id-token: write
      contents: read
    with:
      aws-account-id: '706717726402'
      environment: dev
      container-version: 'v0.0.1'
      registry-name: optimisation-function

  DeployToDev:
    name: Deploy to Development
    uses: ./.github/workflows/deploy-workflow.yaml
    needs:
      - BuildContainer
    permissions:
      id-token: write
      contents: read
    with:
      aws-account-id: '706717726402'
      environment: dev

#  DeployToStaging:
#    name: Deploy to Staging
#    uses: ./.github/workflows/deploy-workflow.yaml
#    needs:
#      - DeployToDev
#    permissions:
#      id-token: write
#      contents: read
#    with:
#      aws-account-id: '072193711147'
#      environment: staging

